name: Build-Test-Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a test
        run: echo "✅ Build and test passed successfully"

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release stage
        run: echo "🚀 Ready to release"
